# Generated by Django 2.1.3 on 2018-11-25 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('value', models.IntegerField(default=0)),
                ('letter', models.CharField(max_length=2)),
                ('student', models.CharField(max_length=15)),
                ('teacher', models.CharField(max_length=15)),
            ],
        ),
    ]
